// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD18Ivz8pQbiIilIE6WWGciQxDW6xz2K5w',
    appId: '1:4659292471:web:66835d809bb915dd1b92b2',
    messagingSenderId: '4659292471',
    projectId: 'week8-crud',
    authDomain: 'week8-crud.firebaseapp.com',
    storageBucket: 'week8-crud.firebasestorage.app',
    measurementId: 'G-FLPD1J6WD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBewPE3Zac-TlA0yV1mFXjddfZvtxv4VR0',
    appId: '1:4659292471:android:37cefe1c235a6cec1b92b2',
    messagingSenderId: '4659292471',
    projectId: 'week8-crud',
    storageBucket: 'week8-crud.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH1tXgdTKxOIm0FdHu-lQuHEB65ZE226Y',
    appId: '1:4659292471:ios:3b25539a33bc48171b92b2',
    messagingSenderId: '4659292471',
    projectId: 'week8-crud',
    storageBucket: 'week8-crud.firebasestorage.app',
    iosBundleId: 'com.example.week8Crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH1tXgdTKxOIm0FdHu-lQuHEB65ZE226Y',
    appId: '1:4659292471:ios:3b25539a33bc48171b92b2',
    messagingSenderId: '4659292471',
    projectId: 'week8-crud',
    storageBucket: 'week8-crud.firebasestorage.app',
    iosBundleId: 'com.example.week8Crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD18Ivz8pQbiIilIE6WWGciQxDW6xz2K5w',
    appId: '1:4659292471:web:b21500ffaf9123991b92b2',
    messagingSenderId: '4659292471',
    projectId: 'week8-crud',
    authDomain: 'week8-crud.firebaseapp.com',
    storageBucket: 'week8-crud.firebasestorage.app',
    measurementId: 'G-WEWCHCYHL4',
  );
}
